// <auto-generated />
namespace Web_API_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class editInPriceOfProdcut : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editInPriceOfProdcut));
        
        string IMigrationMetadata.Id
        {
            get { return "202104062213099_editInPriceOfProdcut"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
